# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='shortBio',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
