# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('t07_08', models.PositiveIntegerField()),
                ('t08_09', models.PositiveIntegerField()),
                ('t09_10', models.PositiveIntegerField()),
                ('t10_11', models.PositiveIntegerField()),
                ('t11_12', models.PositiveIntegerField()),
                ('t12_13', models.PositiveIntegerField()),
                ('t13_14', models.PositiveIntegerField()),
                ('t14_15', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='shortBio',
            field=models.CharField(default='not available', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='privatetimetable',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
    ]
