# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20171020_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5)),
                ('t7_8', models.PositiveIntegerField()),
                ('t8_9', models.PositiveIntegerField()),
                ('t9_10', models.PositiveIntegerField()),
                ('t10_11', models.PositiveIntegerField()),
                ('t11_12', models.PositiveIntegerField()),
                ('t12_13', models.PositiveIntegerField()),
                ('t13_14', models.PositiveIntegerField()),
                ('t14_15', models.PositiveIntegerField()),
            ],
        ),
    ]
