# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20171020_2104'),
        ('mainApp', '0002_auto_20171021_1936'),
    ]

    operations = [
    ]
