# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_privatetimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetimetable',
            name='tutor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
            preserve_default=False,
        ),
    ]
