# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_privatetimetable_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatetimetable',
            old_name='t7_8',
            new_name='t07_08',
        ),
        migrations.RenameField(
            model_name='privatetimetable',
            old_name='t8_9',
            new_name='t08_09',
        ),
        migrations.RenameField(
            model_name='privatetimetable',
            old_name='t9_10',
            new_name='t09_10',
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
    ]
