# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20171022_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatetimetable',
            name='t07_08',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t08_09',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t09_10',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t10_11',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t11_12',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t12_13',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t13_14',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='privatetimetable',
            name='t14_15',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
