# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20171022_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
