# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20171020_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatetimetable',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
    ]
