# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20171022_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
