# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20171020_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5)),
                ('t07_08', models.PositiveIntegerField()),
                ('t08_09', models.PositiveIntegerField()),
                ('t09_10', models.PositiveIntegerField()),
                ('t10_11', models.PositiveIntegerField()),
                ('t11_12', models.PositiveIntegerField()),
                ('t12_13', models.PositiveIntegerField()),
                ('t13_14', models.PositiveIntegerField()),
                ('t14_15', models.PositiveIntegerField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor')),
            ],
        ),
    ]
