# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20171022_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time_start', models.TimeField()),
                ('duration', models.TimeField()),
                ('status', models.CharField(choices=[('BOOKED', 'booked'), ('LOCKED', 'locked'), ('STARTED', 'started'), ('ENDED', 'ended'), ('CANCELLED', 'cancelled')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_start', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='privatetimetable',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Wallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='course',
            field=models.ManyToManyField(blank=True, to='mainApp.Course'),
        ),
        migrations.DeleteModel(
            name='PrivateTimetable',
        ),
        migrations.AddField(
            model_name='unavailableslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='bookedslot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student'),
        ),
        migrations.AddField(
            model_name='bookedslot',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor'),
        ),
    ]
