# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='t07_08',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='day',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t08_09',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t09_10',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t10_11',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t11_12',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t12_13',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t13_14',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='t14_15',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='tutor',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
            preserve_default=False,
        ),
    ]
