# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20171030_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedslot',
            name='date',
            field=models.DateField(),
        ),
    ]
