# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20171031_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailableslot',
            name='duration',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedslot',
            name='duration',
            field=models.FloatField(),
        ),
    ]
