# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20171031_0330'),
        ('mainApp', '0008_auto_20171020_2029'),
    ]

    operations = [
    ]
