# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_merge_20171031_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatetimetable',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivateTimetable',
        ),
    ]
