# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20171110_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='booking_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.BookedSlot'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Wallet'),
        ),
    ]
