# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20171111_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWallets',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Wallet')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=('mainApp.wallet',),
        ),
    ]
