# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_specialwallets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialWallets',
            new_name='SpecialWallet',
        ),
    ]
