# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20171112_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='party',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_id',
        ),
        migrations.AlterField(
            model_name='specialwallet',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
