# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20171112_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Transaction')),
                ('transaction_nature', models.CharField(choices=[('SESSIONBOOKED', 'sessionBooked'), ('SESSIONCANCELLED', 'sessionCancelled')], max_length=20)),
                ('tutorCharges', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('booking_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.BookedSlot')),
                ('other_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_party', to='mainApp.User')),
            ],
            bases=('mainApp.transaction',),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Transaction')),
                ('transaction_nature', models.CharField(choices=[('FUNDSADDED', 'fundsAdded'), ('FUNDSWITHDRAWN', 'fundsWithdrawn')], max_length=20)),
                ('wallet_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Wallet')),
            ],
            bases=('mainApp.transaction',),
        ),
    ]
