# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_sessiontransaction_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontransaction',
            name='booking_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.BookedSlot'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Wallet'),
        ),
    ]
