# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20171112_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedslot',
            name='rate',
        ),
    ]
