# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_remove_bookedslot_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedTutor',
            fields=[
                ('tutor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Tutor')),
            ],
            bases=('mainApp.tutor',),
        ),
        migrations.CreateModel(
            name='PrivateTutor',
            fields=[
                ('tutor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainApp.Tutor')),
                ('session_rate', models.PositiveIntegerField()),
            ],
            bases=('mainApp.tutor',),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='rate',
        ),
    ]
