# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_auto_20171113_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='polymorphic_ctype',
        ),
    ]
