# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_auto_20171113_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatetutor',
            old_name='session_rate',
            new_name='rate',
        ),
    ]
