# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_auto_20171114_2021'),
        ('mainApp', '0015_course_university'),
    ]

    operations = [
    ]
