# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_merge_20171115_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='university',
        ),
    ]
