# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_remove_tutor_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('rating', models.PositiveIntegerField()),
                ('reviewtype', models.CharField(choices=[('ANONYMOUS', 'anonymous'), ('NONANONYMOUS', 'nonanonymous')], max_length=9)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.BookedSlot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Tutor')),
            ],
        ),
    ]
