# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_remove_tutor_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='university',
            field=models.ManyToManyField(blank=True, to='mainApp.University'),
        ),
    ]
