# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_tutor_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='isActivated',
            field=models.BooleanField(default=True),
        ),
    ]
