# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_auto_20171124_1823'),
        ('mainApp', '0034_review'),
    ]

    operations = [
    ]
