# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableslot',
            name='day',
        ),
        migrations.AddField(
            model_name='unavailableslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
